# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-14 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invictus', '0002_reg_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idno', models.IntegerField()),
                ('id_front', models.ImageField(upload_to='/home/gathage/jungle/Sacco/invictus/static/invictus/uploads/ids/')),
                ('id_back', models.ImageField(upload_to='/home/gathage/jungle/Sacco/invictus/static/invictus/uploads/ids/')),
                ('KRA', models.FileField(upload_to='/home/gathage/jungle/Sacco/invictus/static/invictus/uploads/kra/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
