# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-14 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invictus', '0003_uploads'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Uploads',
        ),
    ]
