# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-15 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invictus', '0010_auto_20180215_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='password',
            new_name='password1',
        ),
    ]
