# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-19 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invictus', '0013_auto_20180215_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reg_members',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
