# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-19 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import invictus.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('invictus', '0014_auto_20180219_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='passport',
            field=models.FileField(null=True, upload_to=invictus.helpers.RandomFileName('/home/gathage/jungle/Sacco/invictus/static/invictus/uploads/passport/')),
        ),
    ]
