# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-28 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invictus', '0015_uploads_passport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_no', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.IntegerField()),
                ('acc_balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_no', models.IntegerField()),
                ('trans_time', models.DateTimeField(auto_now_add=True)),
                ('deposit', models.IntegerField()),
                ('acc_balance', models.IntegerField()),
            ],
        ),
    ]
