# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-01 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invictus', '0016_accounts_transact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='email',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='phone',
        ),
    ]
