# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-02 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invictus', '0017_auto_20180301_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='fixed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_no', models.IntegerField()),
                ('trans_time', models.DateTimeField(auto_now_add=True)),
                ('acc_balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='jipange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_no', models.IntegerField()),
                ('trans_time', models.DateTimeField(auto_now_add=True)),
                ('acc_balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='timiza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_no', models.IntegerField()),
                ('trans_time', models.DateTimeField(auto_now_add=True)),
                ('acc_balance', models.IntegerField()),
            ],
        ),
    ]
