# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-06 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invictus', '0018_fixed_jipange_timiza'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='timiza',
            new_name='Fixed_Acc',
        ),
        migrations.RenameModel(
            old_name='jipange',
            new_name='Jipange_Acc',
        ),
        migrations.RenameModel(
            old_name='fixed',
            new_name='Timiza_Acc',
        ),
    ]
