# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-07 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invictus', '0019_auto_20180306_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_no', models.IntegerField()),
                ('question', models.CharField(max_length=100)),
                ('trans_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
